### ISSUE TITLE
/mpet command errors console

### ISSUE THREAD

**Issue by lowkeyHero** [danielntech/miniaturepets#10]
/mpet works for all opped players, but not for players given the miniaturepets.spawn node

[https://pastebin.com/j8H495QC]

**Comment by danielntech** [comment]
I'll transfer that for review by our developers, be sure we'll take care of that ASAP.

For the mean time, try making a copy of your configs and delete them, it will auto generate them from scratch and then you could see if it's your configuration that caused the issue.

**Comment by lowkeyHero** [comment]
That didn't fix the issue.  I removed the gui and main config and restarted.  Still the same

**Comment by danielntech** [comment]
Thanks for the update, I'll write it down in the incident report, I'll hope an update comes soon.

**Comment by lowkeyHero** [comment]
if i remove the permission the error goes away

**Comment by lowkeyHero** [comment]
any update?

**Comment by danielntech** [comment]
This has been resolved and should be seen in future updates.
