### ISSUE TITLE
Pet gliding bug

### ISSUE THREAD

**Issue by danielntech** [danielntech/miniaturepets#11]
MPets debug: https://pastebin.com/etzvH5Pm
Short desc: So all the time I have my pet summoned it teleports to me when I'm flying and slowly glides down. It's really weird lol
Steps to reproduce: 1. just spawn a pet 2. fly around
Proof: https://youtu.be/PLvmzOY9D48

https://github.com/danielntech/miniaturepets/issues/8

**Comment by TrollC** [comment]
Why did you copy the issue I made?

**Comment by danielntech** [comment]
I honestly have no idea why it happend.
Probably a bug.
