### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by alexdemond** [danielntech/miniaturepets#13]
Each pet has a stat gui within some attributes like level,hunger, knowledge,strength,etc.the bar displays your pets' status(like Hunger |||||| 100%.)You have to feed them,have a walk or exercise with them,take them to school to learn something..

I got this idea from some games,i wonder if you would like to add it.
Btw please fix dropping chicken issue,i can easily kill my pet and get a raw chicken from it,i'm using 1.9.4

**Comment by alexdemond** [comment]
Here is the example of going to school--call the pet,entering command/study,the pet will leave you for some hours or even some days to improve 'knowledge'.

**Comment by alexdemond** [comment]
Feature 2,We can dress the pet like giving them a hat

**Comment by SirBailey** [comment]
Seems like a nice idea but a plugin already does this but not custom pets. Also, when you are leveling up your pet with new knowledge what is the point? Does it do anything? Most people using this plugin will use it for a lobby or other type of non-PvP game type since they do get in the way of PvPing. I would like to know more about this.

**Comment by danielntech** [comment]
You can make these with MythicMobs I believe, I'm not sure, if not then with the API. But this suggestion is rejected because this is not the point of the plugin and it has nothing to do with the current ideal.

**Comment by alexdemond** [comment]
Excuse me,How can i hook it with mythicmobs?Even there is nothing in the plugin mentioning mythicmobs...

**Comment by danielntech** [comment]
I don't know, I presume it can be done with MythicMobs. I'm not sure. We didn't develop MM so we can't provide support for it.

**Comment by alexdemond** [comment]
So why did the plugin introduced that it can hook with mythicmobs...
