### ISSUE TITLE
Command Message Bug

### ISSUE THREAD

**Issue by ghost** [danielntech/miniaturepets#16]
Long Description: When you do the command "/mpet ride" the message will be "Pets > You do not have a pet!" (my own set message), but when you do "/mpet remove" the message will be "Pets >You do not have a pet!". So it takes the same message but some commands are missing a space between the message and the prefix.

Image: https://imgur.com/nchlGlR

MPets Dump Link: When I did "/mpet dump" it gave me an error "There was a problem exporting the pastebin".

**Comment by SirBailey** [comment]
Same bug with /mpet name.

**Comment by danielntech** [comment]
Hi, please update to the latest version.

**Comment by danielntech** [comment]
Closed due to OG being banned from GitHub.
