### ISSUE TITLE
Suggestion - Pet showcasing satues

### ISSUE THREAD

**Issue by Asodey** [danielntech/miniaturepets#18]
It would be cool if we had a /pet statue menu, it will open a menu with ALL the pets that we have, and we will be able to place them at the place where we stand, and the pets wont move or walk, they will stand as statues so people could see how does the pet look like before getting that one

**Comment by SirBailey** [comment]
I think this is coming in v2.0 I believe.

**Comment by danielntech** [comment]
Hi, it's currently planned, it might take time though.
