### ISSUE TITLE
Pet show feature

### ISSUE THREAD

**Issue by AlonsoAliaga** [danielntech/miniaturepets#2]
Suggestion:A feature that allow us (Server owners) to create a pet show on a block.
How will improve servers: It will allow players see how pets look like before purchasing so they can decide which pet they like the most. Also it will promote donations in servers.
Additional information: Possibiltity of adding holograms lines (pet name, server name, price, others maybe). Option to decide time in second between pet loop. Command like: /mpet setshowlocation [time in seconds between loop]

**Comment by danielntech** [comment]
Your'e suggestion has been noted and submitted for review, please hold on. We'll get back to you soon.

**Comment by danielntech** [comment]
This feature was approved and will come in future updates.
