### ISSUE TITLE
Color Error

### ISSUE THREAD

**Issue by SirBailey** [danielntech/miniaturepets#21]
I know something like this is already open but I believe you won't really see it since you didn't reply to that one.

So, when you remove a users pet the color will reset back to &r.

https://i.gyazo.com/18d04f8cb8246d61cc622f197d95cb1e.png

**Comment by SirBailey** [comment]
Not the same I guess now that I think about it, but it is a message bug.
https://github.com/danielntech/miniaturepets/issues/16

So, when you remove a players pet this message will show up https://i.gyazo.com/18d04f8cb8246d61cc622f197d95cb1e.png.
If you look at the message "'s pet" is in white when it should be in Red.
Addon to this suggestion, let us changed this message in the config also.

**Comment by danielntech** [comment]
Not a problem, suggestion and bug forwarded. Anything else I can do for you?

**Comment by SirBailey** [comment]
That's it for now, thank you. If I find any more bugs or have any suggestions I'll create a new post.

**Comment by NacOJerk** [comment]
Fixed via config change
