### ISSUE TITLE
[Suggestions] for 2.0

### ISSUE THREAD

**Issue by TrollC** [danielntech/miniaturepets#22]
Hey there,
I have some suggestions for version 2.0
First one is making pets able to get in combat with monsters on specific servers (option in config).
Second one is when someone is disguised in a pet their name should be shown in tab and above their pet.
And the last one, is a known bug where parts of pet go wild on different versions.
I am talking about this bug:
![2018-07-11_17 08 03](https://user-images.githubusercontent.com/28529235/42584221-5a02dce4-853b-11e8-983d-b8917fdd1372.png)
![2018-07-11_17 08 05](https://user-images.githubusercontent.com/28529235/42584222-5a2e8fe2-853b-11e8-925b-8c97798be0f2.png)

I think the way to fix this is checking the version of a player and applying different conditions depending on that.

I really love mpets and I hope you will take my suggestions in consideration.

**Comment by danielntech** [comment]
First one is irrelevant, could be accomplished with the API.
Second one is the same as the first.
Third one - We've recently discovered that some pets have this issue, and it's not the plugin itself.

Appreciate the report, if you find me wrong, please reopen this.
