### ISSUE TITLE
item durability on armour stand head

### ISSUE THREAD

**Issue by ThatTaz** [danielntech/miniaturepets#23]
Suggestion: Allow the pet maker to place items with durability (sword, hoe, etc) on the armour stand head, allowing servers with custom textures to utilize it.
How will it improve the plugin: Will open a lot more options for custom pets.
Any examples or additional information: Workaround currently is to put the item in the hand of the armour stand but this makes it difficult to work with.

**Comment by danielntech** [comment]
Hi, we already have a similar issue. I'll close this suggestion for duplication.
