### ISSUE TITLE
Mpets structuring

### ISSUE THREAD

**Issue by AtomixCM** [danielntech/miniaturepets#24]
Hello,

I'm going to copy the message I sent to the EnderPigs account on spigot.

Hey m8,

First off, I just want to thank you for creating the resource MiniaturePets. It is plugins like this one that help to make the minecraft community unique.

What I wanted to ask you was if there were going to be any efforts made to increase the actual functionality of the plugin. The ability to make pets from items is stellar, however, movement seems to pull the pets apart a bit. 

Do you think you could work to make the armorstands (or structures) move as one instead of as single units? I think something like this would improve the plugin as a whole because the quality of the pets would look much better.

Thanks again! Looking forward to your response.

Hit me up on discord if that works for you :) CM_lectric #3148

**Comment by danielntech** [comment]
Hi, first of all, welcome to our community 👍 
I saw you've just joined our Discord server, so you should point an eye for the #2-point-0 channel.
We will occasionally post spoilers about the new updates, besides what already known.

I hope we'll see what you suggested here in the next version, can't guarantee it.

Have a good one :)

**Comment by danielntech** [comment]
Hi, I think it's not really relevant anymore because of the 2.0 release, if you find me wrong please reopen this.
