### ISSUE TITLE
Pet name not always saving

### ISSUE THREAD

**Issue by TrollC** [danielntech/miniaturepets#25]
Hello,
I kinda found a bug.
When I do /pet setname something for the first time it saves fine but when I do it further on after server restart it resets back to the old one. I'm using mysql. Also names dont sync between servers.

**Comment by danielntech** [comment]
Hi, sorry for the delayed response, I've submitted this to our development team.

**Comment by NacOJerk** [comment]
Well the name updates only on plugin disable so if the server is closed incorrectly the names wont update
