### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by AlonsoAliaga** [danielntech/miniaturepets#28]
Placeholders like:
%miniaturepets_pet_status% - shows "Unlocked" or "Locked" or configurable. To use in game gui lore.
Not just "Yes" "No"
%miniaturepets_unlocked% - shows unlocked for other gui that supports placeholderapi
%miniaturepets_locked% - shows unlocked for other gui that supports placeholderapi
%miniaturepets_total% - shows total of mpet files, unlocked (by permission) to be used in mpet files, 
would be really appreciated.
Also one showing percentage like "unlocked * 100 / total"

**Comment by danielntech** [comment]
Hi, truthfully I find no actual purpose for placeholders in MPets.
It won't really help anyone, it just slows down the plugin.
