### ISSUE TITLE
gui does'nt works 1.13.1

### ISSUE THREAD

**Issue by Yukyxy** [danielntech/miniaturepets#29]
Hello 
https://youtu.be/-dnP7Sri0GA
- gui buttons delete / renames / disguises animals / teleport ... does'nt works.

**Comment by NacOJerk** [comment]
Are you using plugman ?

**Comment by Yukyxy** [comment]
no

**Comment by danielntech** [comment]
Please send your DUMP file.

**Comment by Yukyxy** [comment]
https://pastebin.com/hqDhCLxk

**Comment by Yukyxy** [comment]
This is the file petGUI.yml that buggy...
Material WOOL does'nt works and RED_WOOL too in 1.13.1 => https://pastebin.com/qkBuDKqJ
I tried the APPLE item it works fine now

**Comment by NacOJerk** [comment]
Odd maby the name was changed in 1.13

**Comment by BillyGalbreath** [comment]
This is caused by the compatibility layer in CraftBukkit on 1.13.x builds. Plugins compiled against 1.12 will still work on 1.13.x, but only when using the `legacy` names.

@Yukyxy set the value to `LEGACY_WOOL` and it should work.

**Comment by danielntech** [comment]
This was resolved in recent updates.
