### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlonsoAliaga** [danielntech/miniaturepets#30]
First error when trying to ride the pet. 
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.addPassenger(Lorg/bukkit/entity/Entity;)Z 
it should support also 1.8.8, right? Why it needs addPassenger method?
Second: Chicken spawns 3 or 4 blocks away from the armorstand and takes up to one minute to update. I'll try to get an ss of this.
Third: Some pets are really slow, they are buggy. No error in console. They appear and move in slow motion.
Fourth: some time pets break, like they body here and the head blocks away. No error in console.
And error when trying to interact with some mpets.
https://www.hastebin.com/hicecupeme.pl 
Version: Spigot 1.8.8

**Comment by danielntech** [comment]
Hi, I'll pass it forward to our development team.

**Comment by danielntech** [comment]
Hi, your first and fifth error were fixed, the rest are still waiting response.

**Comment by NacOJerk** [comment]
Fixed already

**Comment by NacOJerk** [comment]
Except the fourth
