### ISSUE TITLE
 bug movement 1.13.1

### ISSUE THREAD

**Issue by Yukyxy** [danielntech/miniaturepets#31]
the movement is buggy...
it's scary o_o...

https://youtu.be/h0BknPMQBr8

**Comment by NacOJerk** [comment]
Hey can you please a /mpet dump
Also does this only  occur with the duck pet ?

**Comment by Yukyxy** [comment]
https://pastebin.com/hqDhCLxk
duck / penguin / Dove

**Comment by danielntech** [comment]
@NacOJerk

**Comment by NacOJerk** [comment]
This is a bit odd does but it seems like 1.13 changed yaw agian I will make a fix probably pretty soon
