### ISSUE TITLE
Mob Spawning Behaviour 

### ISSUE THREAD

**Issue by robert-beckley** [danielntech/miniaturepets#32]
*Short description:*
Upon spawning the mob ignites. 

*Long description:*
The Zombie and Skeleton will light on fire if out during the day. 

*Actions to repeat / ways of reaching the bug:*
Spawn in a zombie or skeleton

*Miniature Pets Dump Link:*
https://pastebin.com/7tNpw1vr

![image](https://user-images.githubusercontent.com/41904721/45284530-2fc9bb00-b524-11e8-8552-65e77e4b5b00.png)
![image](https://user-images.githubusercontent.com/41904721/45284584-440db800-b524-11e8-8b44-a132c0955fc8.png)

**Comment by danielntech** [comment]
Hi, thank you for this report, I'll forward this to our development team.

**Comment by danielntech** [comment]
This issue has been fixed and will be added to the next release.
