### ISSUE TITLE
Enderman pet bug

### ISSUE THREAD

**Issue by ThatTaz** [danielntech/miniaturepets#33]
Enderman pet teleports

You can also ride the enderman pet, it teleport and glitch outside a servers map

Summon an enderman pet and ride it

N/A

**Comment by danielntech** [comment]
Hi, the Enderman pet is not created by us and you should contact the creator.

**Comment by SirBailey** [comment]
This isn't a problem a pet creator can fix, the enderman is still acting likes it's a normal mob so it randomly teleports. This is a bug and needs to be reopened.

**Comment by danielntech** [comment]
@SirBailey Does it refer to a Vanilla mob?

**Comment by SirBailey** [comment]
Yes, this goes for all other Vanilla mobs. I haven't tested most but if an Enderman can teleport why can't a sheep just randomly eat grass (haven't tested if they do),  you can trade with the villagers (fact, you can). Zombies and Skeletons burn in daylight (also true). Vanilla mobs need to lose all they're API.

**Comment by danielntech** [comment]
Ah I see, it's an addition to issue #36.
I'll forward this to our development team, it should definitely be fixed. My bad.

**Comment by SirBailey** [comment]
We, I mean they shouldn't be able to. Trading with a villager that you can just spam spawn in is kind of overpowered.
