### ISSUE TITLE
Vanilla pets issues

### ISSUE THREAD

**Issue by xion87** [danielntech/miniaturepets#34]
I used the vanilla minaturepets pack on download site. these pets are not interactive, also villager will sell stuffs. (i mean no minature pets gui on click).
Also hostile mobs don't spawn (example, zombie skeleton ecc, instead by using another plugin like simplepets, it work)

**Comment by danielntech** [comment]
Hi, this was fixed with the latest version, please download it.

**Comment by xion87** [comment]
latest version of what? i already using miniaturepets v2.0.2

**Comment by danielntech** [comment]
Ah, this wasn't released yet then. It would definitely be fixed in the next version.

**Comment by xion87** [comment]
Also i would love if you can add on gui on these vanilla pets for edit the "baby" version or wool colors, ecc :)

**Comment by danielntech** [comment]
This is a nice feature, please open it in the suggestion format so I could pass it to our developers.

**Comment by xion87** [comment]
Done :) https://github.com/danielntech/miniaturepets/issues/36
