### ISSUE TITLE
Plotsquared support

### ISSUE THREAD

**Issue by xion87** [danielntech/miniaturepets#35]
*Suggestion:*
Make the pets not disapear if kill-road feature is enabled (it delete all armor stand on road)

**Comment by danielntech** [comment]
Hi, then you should disable the KillRoad feature, we currently don't feature support for it.

**Comment by xion87** [comment]
you just have use the plotsquared api for avoid pet being delete :) if you need help there is the plotsquared discord https://discord.gg/WzsDtT

**Comment by danielntech** [comment]
Hi, there is no demand for that so we won't do it, there is a clear solution and I've stated it in my previous message. We currently do not intend to support this.
