### ISSUE TITLE
Make the head gui load async

### ISSUE THREAD

**Issue by xion87** [danielntech/miniaturepets#37]
*Suggestion:* 
Make the head gui load async  because it cause some lag spikes https://timings.aikar.co/?id=8b97b770e49a4263ad3862b351f1c743

*How will it improve the plugin:* 
Make it async :)

*Any examples or additional information:*
head database plugin is async :)

**Comment by danielntech** [comment]
Your suggestion was accepted and implemented in the latest update as a configurable option of the plugin. Thank you!
