### ISSUE TITLE
Suggestion:Combatting feature

### ISSUE THREAD

**Issue by alexdemond** [danielntech/miniaturepets#4]
Suggestion:Could you add a feature of combatting likes mypet,combatpet or rpgpet,which allows them to fight with other.Each pet has his own stats and attributes,and the players can strengthen them.

**Comment by danielntech** [comment]
I'll have this investigated, please hold on as we are checking the matter. It might take some time.

**Comment by danielntech** [comment]
Dear Alex, I'll quote the Developer's answer:
"Unrelated to the main purpose of the plugin might be done through the API by someone who wants it."

In short, your suggestion was declined.

Thanks for your understanding.
