### ISSUE TITLE
Pets don't spawn in WG region with mob-spawning: false

### ISSUE THREAD

**Issue by BiGUNMAN** [danielntech/miniaturepets#41]
*Short description:* 
Miniature pets don't spawn in WorldGuard regions with mob-spawning set to false. I've set WorldGuard in my config set to false and when I spawn a pet, they automatically despawn and the plugin says "your pet was removed".

*Actions to repeat / ways of reaching the bug:* 
Create a WG region, set mob-spawning to false, and spawn a mob in it.

*Miniature Pets Dump Link:*
Unavailable as of yet.

**Comment by danielntech** [comment]
As soon as you send a dump link I could help you better.

**Comment by BiGUNMAN** [comment]
https://pastebin.com/PnN3YLcE

**Comment by danielntech** [comment]
We don't support PlugMan, please remove it and try again.

**Comment by BiGUNMAN** [comment]
I'm not loading the plugin with plugman, there should be absolutely no
problem with it.

**Comment by danielntech** [comment]
Please try to disable it, if it doesn't work then you should manually check which plugin is interfering with Miniature Pets.

**Comment by BiGUNMAN** [comment]
I've already disabled it and it still happens.

**Comment by danielntech** [comment]
Just caught my eye that "I've set WorldGuard in my config set to false", it should be true if you do use WorldGuard.

**Comment by BiGUNMAN** [comment]
I've set it to "true" and it makes absolutely no difference. This is my current config: https://pastebin.com/zayft8PY

**Comment by BiGUNMAN** [comment]
That did the trick.

**Comment by danielntech** [comment]
Sweet!
