### ISSUE TITLE
Crash on plotsquared world after some hours

### ISSUE THREAD

**Issue by xion87** [danielntech/miniaturepets#42]
I never have any issue with crash until i put the plugin miniaturepets on plotsquareded world (creative gamemode, worldedit)
this is the log https://gist.github.com/xion87/911e05102e9363ec8ee6142de525579a
I am 100% sure that is caused by miniature pets since we dont allowe entity to spawn (seem the cause is a chicken, miniaturepets as i remember it use fake chicken)
Server version 1.12.2 paperspigot

**Comment by xion87** [comment]
any news about this issue?

**Comment by danielntech** [comment]
No, it might take time since it's not only on our end.

**Comment by NacOJerk** [comment]
Can you please send the actual area of the crash it is really messy

**Comment by xion87** [comment]
> Can you please send the actual area of the crash it is really messy

I don't generate the crash, just that log

**Comment by danielntech** [comment]
Basically, we don't officially support PaperSpigot and it's really hard to understand the source of the error. Would you please send just the specific area of the crash within the code?
