### ISSUE TITLE
MySQL issue: The value 'false?useSSL=false' is not in this set.

### ISSUE THREAD

**Issue by andrewkm** [danielntech/miniaturepets#46]
Miniature Pets 2.0.3
MySQL: 5.7.23-0ubuntu0.16.04.1-log

Config:

```
useMySQL: true
hostName: host
port: 'port'
databaseName: 'name?useSSL=false'
username: username
password: 'password'
method: MySQL
autoReconnect: false
```

Error: https://pastebin.com/raw/7hhCSdK7

Miniature Pets is detecting it as false?useSSL=false using the above config.
Not having this problem with any other MySQL setups.

Not using ?useSSL=false in my database name works fine with miniature pets, however this option is necessary for my setup. Please look into this.

**Comment by NacOJerk** [comment]
I will add this to the options

**Comment by NacOJerk** [comment]
O use ssl is by config false

**Comment by NacOJerk** [comment]
So Im gonna mark this as solved

**Comment by danielntech** [comment]
@andrewkm

**Comment by andrewkm** [comment]
Not necessarily solved as you shouldn’t be forcing SSL as false. This should be done by the users via the config. This is the only plugin I’ve seen do such a thing, really unnecessary. @nacojerk @danielntech
