### ISSUE TITLE
Pets walking through blocks Spigot 1.8.8

### ISSUE THREAD

**Issue by AtomixCM** [danielntech/miniaturepets#48]
*Short description:* 
Pets walk through blocks
*Long description:* 
Pets are following strangely, and not abiding by usual minecraft behavior
*Actions to repeat / ways of reaching the bug:* 
Spawn a pet and walk around
*Miniature Pets Dump Link:*
https://pastebin.com/9gxPP6kR

**Comment by danielntech** [comment]
What is your exact Minecraft version? 1.8.x?

**Comment by AtomixCM** [comment]
1.8.8

**Comment by danielntech** [comment]
Could you please film this or send this as a gif?

**Comment by SirBailey** [comment]
I've already sent this to NacOJerk. It seems to only happen in 1.8.8.
https://i.imgur.com/rBUgYHj.gif
The reason the "pet" walks through walls is that the armorstands are not near the anchor.

**Comment by danielntech** [comment]
I see, in that case there is no need for another issue, it's on the queue.
