### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by FactionsOlzie** [danielntech/miniaturepets#5]
Suggestion - You can use the player's head as the icon of the /mpets gui.
Suggestion - Choose what slots you want them in. ect, Remove your pet, Change your pets name, "spacer".
Suggestion - Possibly Add actual animals as a pet :wink:

**Comment by danielntech** [comment]
This has been sent for processing, thank you :)

**Comment by danielntech** [comment]
Regarding your third suggestion, it was accepted and will probably come out in version 1.6

Regarding the others, still no response.

**Comment by danielntech** [comment]
Hi, suggestion 3 was added, suggestion 2 will be added soon, suggestion 1 was added.
