### ISSUE TITLE
Pets That Depend on Skulls of Offline Players won't Load

### ISSUE THREAD

**Issue by NolanMC** [danielntech/miniaturepets#50]
*Description:* 
I have pets on my server that depend on the skulls of offline players, and when you try to spawn them in, they will not load. There is no stacktrace or error messages with this. If the person comes online to the server, the pet will load perfectly fine. I am a few versions behind on the updates (2.0.3), but from what I could tell the changes between the 2.0.3 and 2.0.5 wouldn't affect this issue. 

*Actions to repeat / ways of reaching the bug:* 
1. Make a pet that depends on a player skull of an offline player
Example items.yml: https://gist.github.com/NolanMC/7028db9dea8c492fc60283371e3beb10
In the example that is linked, I used Notch. This pet will not load until you change Notch to the username of an online player on your server.

*Miniature Pets Dump Link:* 
https://pastebin.com/B6YdHJTR

**Comment by danielntech** [comment]
Hi, that is not a bug, that's why we recommend using textures instead of players heads. You should ask questions about how to create pets on our community discord server.

https://discord.gg/5WDYySv
