### ISSUE TITLE
Bug in 1.13.1

### ISSUE THREAD

**Issue by Amiroslo** [danielntech/miniaturepets#51]
*Short description:* https://pastebin.com/8Cga6RKq

*Long description:* https://pastebin.com/8Cga6RKq
 
*Actions to repeat / ways of reaching the bug:* Just running up the server

*Miniature Pets Dump Link:*

**Comment by danielntech** [comment]
Hi, please disable worldguard = true in the MPets config. It appears you enabled it while not having Worldguard.

**Comment by Amiroslo** [comment]
i do have WG, but im using latest for 1.13
http://builds.enginehub.org/job/worldguard?branch=master

**Comment by danielntech** [comment]
Please send your dump link.

**Comment by danielntech** [comment]
@Amiroslo please comment in the upcoming day or your issue will be closed.
