### ISSUE TITLE
error console last version v2.0.6 and v2.0.65

### ISSUE THREAD

**Issue by Yukyxy** [danielntech/miniaturepets#52]
serveur version spigot 1.13.1
*Short description:* 
error open GUI / spawn pet ...

error
https://pastebin.com/qhKKPYnA

*Miniature Pets Dump Link:*
https://pastebin.com/RXythQ4K

https://i.postimg.cc/LXKhCTk0/gui.png
I do not have the same thing as on your screen, it may be related? (sorry for my english)

**Comment by Yukyxy** [comment]
In v2.0.65 no error
After to use disguise menu of animal, 
my inventory disappear and my menu itemjoin too...
I must to disconnect reconnect
Once I managed to duplicate items...
[IMG]https://zupimages.net/up/18/40/0hph.png[/IMG]

With the gui menu /mpet open i have no problem

**Comment by NacOJerk** [comment]
Solved sir I think

**Comment by Yukyxy** [comment]
i have this error https://pastebin.com/YncGd9uu Version 2.0.7

**Comment by NacOJerk** [comment]
try redownloading it (I uploaded the wrong file first)

**Comment by Yukyxy** [comment]
yes it's ok ^^
