### ISSUE TITLE
Leftover debug in 2.0.7

### ISSUE THREAD

**Issue by Sikatsu** [danielntech/miniaturepets#53]
*Short description:* 
Theres a lot of leftover debug in the latest version.

*Actions to repeat / ways of reaching the bug:* 
03.10 12:49:29 [Server] INFO hey
03.10 12:49:29 [Server] INFO hey
03.10 12:49:29 [Server] INFO hey

It keeps spamming this in the console on 2.0.7.
Makes the console useless.

**Comment by danielntech** [comment]
Hi, this will be fixed in the next release, sorry for the inconvenience.
