### ISSUE TITLE
Horse Errors

### ISSUE THREAD

**Issue by SirBailey** [danielntech/miniaturepets#56]
*Description:*
You can't ride the horse and it also bends down to eat grass.

*Actions to repeat / ways of reaching the bug:* 
1. Try and ride a horse.
2. Just wait and you'll see the horse randomly bend down.

*Miniature Pets Dump Link:*
https://pastebin.com/ZtyBRhLE

**Comment by danielntech** [comment]
I would pass that over, it indeed appears to be an issue with the latest update, we will notify you via this issue when it is resolved.

**Comment by NacOJerk** [comment]
I will fix this bug by Saturday
