### ISSUE TITLE
[1.13.1] Can't ride pets

### ISSUE THREAD

**Issue by Sikatsu** [danielntech/miniaturepets#57]
Players seem to be able to enter the pet but WASD doesn't move them.

**Comment by danielntech** [comment]
Your report lacks an `/mpet dump` link. Please add it.

**Comment by Sikatsu** [comment]
An RPG pet plugin.

https://www.spigotmc.org/resources/mypet.12725/

**Comment by danielntech** [comment]
I see, I have classed this issue as a bug and a developer will take a look at it shortly.

**Comment by Sikatsu** [comment]
I think after clicking ride and using shift to leave it again, also causes the pet to freeze. It stays stuck on a position and doesn't follow you anymore.

http://prntscr.com/l77khl

**Comment by NacOJerk** [comment]
Hey from what I see the problem is because there is a new 1.13 NMS version 1_13_2 so I will probably solve it by Saturday (when I will release the weekly update)
