### ISSUE TITLE
[MiniaturePets] Couldn't preload reflections

### ISSUE THREAD

**Issue by karlelpro** [danielntech/miniaturepets#58]
*Short description:*  Error with reflections on this plugin

*Long description:*  When I start my server with the plugin, in the console it says me: [MiniaturePets] Couldn't preload reflections

*Actions to repeat / ways of reaching the bug:*  I was stopping the server and reloading it to see if I resolve the bug but nothing yet :(

*Miniature Pets Dump Link:* https://www.spigotmc.org/resources/miniature-pets-boost-up-your-personal-server-with-amazing-customizeable-pets.23991/

**Comment by NacOJerk** [comment]
You didnt post a mpet dump
Please do /mpet dump and provide us the link .

**Comment by NacOJerk** [comment]
From what I understand this issue has already been solved
