### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by liorsl** [danielntech/miniaturepets#6]
Hello,
I am trying to develop a plugin using MPets API and I got into a few problems:
1. APIMob#setSpeed have no effect.
2. APIMob#setMaxHealth and APIMob#setHealth will change the health but reset after the mob is being damaged.
3. There is no option to change the pet's name when it kills someone.

**Comment by danielntech** [comment]
Dear @liorsl, your issue has been sent over for processing and will be taken care of as soon as possible.

Thank you for your patience.

**Comment by liorsl** [comment]
Dear @danielntech,
Putar.
Any update as of yet?

**Comment by danielntech** [comment]
Hello again,
I'm afraid not yet, as of this moment we focus on fixing bugs by priority, we hope to see results soon.

Thanks.

**Comment by danielntech** [comment]
The API will be recoded on the next version. 

Cheers.
