### ISSUE TITLE
My Pets don't move when I tried to control them

### ISSUE THREAD

**Issue by sedez2842** [danielntech/miniaturepets#61]
I updated MPets to last version once I stopped playing minecraft for a while and then I tried to Ride my pets, then they're all uncontrollable. They still follow their owner but if the owner rides them, they stopped moving no matter how owners move/fly.
*Miniature Pets Dump Link:*https://pastebin.com/mnkcNWBU

**Comment by NacOJerk** [comment]
Fixed :)

**Comment by sedez2842** [comment]
It works very well for now.
Thank you so much :D
