### ISSUE TITLE
MySQL Tables not being generated

### ISSUE THREAD

**Issue by Xeyame** [danielntech/miniaturepets#62]
*Short description:* Having some issues with MySQL (Tables not generating)

*Long description:* Basically the SQL statement for creating the tables is wrong.

*Actions to repeat / ways of reaching the bug:* Set up Mpets with an empty mysql database

*Miniature Pets Dump Link:*
Not feeling like sharing all my plugins :)
`User ID: 375094
Nonce : 149528933
Server Online: false
Version : v1_13_R2
Platform : PAPER-SPIGOT`

*Respective log entry*: https://l.xeya.me/rm6wq

**Comment by danielntech** [comment]
Hi, could you please specify what is your SQL software? MySQL, MariaDB, etc.

**Comment by Xeyame** [comment]
Sorry about that, Didn't notice your reply. I am using MySql 5.7.24-0ubuntu0.16.04.1 - (Ubuntu)

**Comment by danielntech** [comment]
Thanks for that, I'm afraid we still need your full dump report to examine conflicts with other plugins.

**Comment by Xeyame** [comment]
Any updates on this issue getting resolved?

**Comment by danielntech** [comment]
Hi @Xeyame, please E-Mail me the JAR you are using to me@danielnaaman.com so we can further examine the issue.

**Comment by Xeyame** [comment]
I am using the latest mpets from spigotmc, together with the latest paper release from [here](https://papermc.io/downloads)

**Comment by danielntech** [comment]
Hi @Xeyame, just to inform you that we are still working on it, I know it takes ages, sorry.

**Comment by NacOJerk** [comment]
Problem fixed .
