### ISSUE TITLE
Pets disabled in specific WorldGuard regions

### ISSUE THREAD

**Issue by Golicraft** [danielntech/miniaturepets#64]
*Suggestion:* Pets disabled in specific worldguard regions

*Why:* If this will be implemented I can use this on my lobbys for example on practice server, survival spawn etc. That had been very cool  

*How will it improve the plugin:* It will help users like me who requests this

*Any examples or additional information:*
Disable pet with disable-pet message when entering a disable-pet worldguard region. When leaving that specifc region the pet will be auto-loaded again? 👍 

Thank you in advance. 🥇

**Comment by danielntech** [comment]
Hi, I'm not a big expert when it comes to WorldGuard but I'm pretty sure that you have to configure it per region through flags, there is definitely a flag for Mobs/Armorstands and it should apply here.

**Comment by Golicraft** [comment]
> Hi, I'm not a big expert when it comes to WorldGuard but I'm pretty sure that you have to configure it per region through flags, there is definitely a flag for Mobs/Armorstands and it should apply here.

Thanks for replying. I would like to use pets for example on my Survival server but not in the pvp arena since it is an advantage for a player. WorldGuard can only stop monsters from spawning, but not removing them after entering a region. 

If the function can be so if you enter a disabled-mpet-region the pet will be toggled off and you will get a message and when you are out of the disabled-mpet-region the pet will me loaded again. 

In that way I can use pets on all my servers and players can have "more fun" with them and showing them around 👍 Thank you in advance.

**Comment by danielntech** [comment]
Hi, this is a nice suggestion but I don't think it will happen anytime soon since there are many solutions that don't involve an update, such as per world permissions and stuff like that, I'd start there.

Thanks for the creative idea though!

**Comment by danielntech** [comment]
Hello again, I have registered it as a suggestion, but for the moment you should know that it might take time. I would try and figure out something else.

Personally, I recommend using the per-world-permissions method since it will be very helpful when trying to use Permissions.

Good day

**Comment by Golicraft** [comment]
> Hello again, I have registered it as a suggestion, but for the moment you should know that it might take time. I would try and figure out something else.
> 
> Personally, I recommend using the per-world-permissions method since it will be very helpful when trying to use Permissions.
> 
> Good day

per-world-permissions? I use pex with MySQL. But okay I can stand with the disabled-worlds but have a new suggestion so will make that thread now. Thanks anyways.
