### ISSUE TITLE
Pets Taking Player Items Out Of Their Hands

### ISSUE THREAD

**Issue by Kalasky** [danielntech/miniaturepets#65]
*Short description:*  Pets are taking my players items.

*Long description:* When they crouch click, it just takes it right out of their hand and it's gone forever. 

*Actions to repeat / ways of reaching the bug:* Continuously crouch right click around or on the pet, sometimes it takes a while sometimes it's the third try. 

*Miniature Pets Dump Link:* Not necessary.

**Comment by danielntech** [comment]
Hi, please send your dump link as it's always necessary. Does this happen with all pets or just vanilla ones?

**Comment by Kalasky** [comment]
I can only do it with the duck, I tried to do about 10 others and nothing. Maybe there are a few more pets that take your tools I am not completely sure. Sometimes it shows it floating and other times it just takes it. In gamemode spectator is shows the armor stand holding it on its arm. 
![duck](https://user-images.githubusercontent.com/42560806/48049209-c694ab80-e152-11e8-9cc7-d383cb5c63a6.png)

**Comment by danielntech** [comment]
Thank you for the clarification and the dump link, I've forwarded your request to our development team. Be patient while we examine this and return with an answer.

**Comment by danielntech** [comment]
Hi @Kalasky, we still don't have news regarding this issue, can you confirm it still happens?

**Comment by NacOJerk** [comment]
Hey can you contact me on discord NacOJerk#0001 
I can't recreate your bug so I can't fix it.

**Comment by danielntech** [comment]
@Kalasky Pending your response.

**Comment by danielntech** [comment]
Per my understanding it was fixed with the latest release. This issue is closed due to no response. Please reopen if necessary.
