### ISSUE TITLE
Custom Head Skulls thread-update

### ISSUE THREAD

**Issue by Golicraft** [danielntech/miniaturepets#67]
*Suggestion:* Update "Custom head skulls" thread

*How will it improve the plugin:* I can make own pets with custom skins

*Any examples or additional information:*
Yes please update: https://github.com/danielntech/miniaturepets/wiki/Creating-Custom-Heads Please fix the server IP it says "unknown host" so I cant type /NMS. Thank you in advance

**Comment by Golicraft** [comment]
Why no replies?

**Comment by danielntech** [comment]
Hi, our Wiki will be rewritten in the upcoming months, for the mean-time, can you be more specific about what you are trying to achieve?

**Comment by Golicraft** [comment]
Hi @danielntech, I would like this because then I can create pets with for example my skull or custom drawed skulls to be like a "block pet" and not only miniatures 👍

**Comment by danielntech** [comment]
Hey, you can create a pet with any skull you wish, you just have to use the [head decoder](https://danielnaaman.com/projects/head-decoder/) tool.

**Comment by Golicraft** [comment]
Can you make an example how it works or is it any wiki? I didn't understand it, sorry

**Comment by Golicraft** [comment]
Please @danielntech

**Comment by Golicraft** [comment]
@danielntech no.... I am asking how to add my own skin head. What did you not understand? I asking for help because the guide doesn't work. And you provided me your website but won't tell me how to actuall use it, because I can't figure it out. I belive it is broken. Can you send discord invite so we can continue there

**Comment by danielntech** [comment]
Here is a Discord invite:
https://discord.gg/5WDYySv

You are free to discuss with the rest of the community about this, but I'm not a pet creator. The #pets channel would help you I believe.

Good day
