### ISSUE TITLE
Medium/Large Slime variants attack players

### ISSUE THREAD

**Issue by Felixx61** [danielntech/miniaturepets#69]
*Short description:* 
Medium/Large slime pet variants will attack any player who runs near/into them.

*Long description:* 
Medium/Large slime pet variants will attack any player who runs near/into them.

*Actions to repeat / ways of reaching the bug:* 
Generate a slime pet and change size to medium/large

*Miniature Pets Dump Link:*

**Comment by danielntech** [comment]
We've decided to remove the slime pack for the moment because of the issues it causes. 

Good day.
