### ISSUE TITLE
MiniaturePets is consuming resources 

### ISSUE THREAD

**Issue by iDhoom** [danielntech/miniaturepets#74]
*Short description:* 
MiniaturePets is consuming a lot of resources (compared to my other plugins)

*Long description:* 
From time to time I make /timings report to watch the server performance, I have noticed that MiniaturePets is consuming a lot of resources (compared to my other plugins) on join/left events, I believe its due to loading/saving data for the players.
https://prnt.sc/lwwsc5
Is there anyway to disable this feature, i'm using the API to handle the pets already.

*Actions to repeat / ways of reaching the bug:* 
Normal day!

*Miniature Pets Dump Link:*
https://pastebin.com/q3rp7PzS

**Comment by NacOJerk** [comment]
I will add an option to disable this.

**Comment by NacOJerk** [comment]
In version 2.1.3 you will find a variable handlePlayerData in config.yml
Disable it and the plugin will stop handling player data

**Comment by NacOJerk** [comment]
Version 2.1.4 *
