### ISSUE TITLE
Errors on login

### ISSUE THREAD

**Issue by MithrandirCraft** [danielntech/miniaturepets#75]
Error on console every time someone logs in:

https://hastebin.com/opomihusij.md

MPets 2.1.25
Spigot 1.13.2

**Comment by MithrandirCraft** [comment]
https://pastebin.com/DCqexjip

**Comment by MithrandirCraft** [comment]
Sorry for insisting, but is that enough?
Thanks for the help.

**Comment by danielntech** [comment]
Hi, per my communication with the developer this was resolved, please update and reopen if you still encounter this issue.
