### ISSUE TITLE
API not working with MythicMobs

### ISSUE THREAD

**Issue by TerraPrimal** [danielntech/miniaturepets#76]
*Short description:* The API is not working with MythicMobs.

*Long description:* This issue has been around for a while now and the Dev of MM (Ash) has been asking for it to be fixed in discord as well as on the forums. 
14 days ago you closed a report advising it has been fixed and it hasn't, I along with a few others would like it to be fixed so we can use it again (I only purchased it for the addon for MM and have yet to be able to use it)

*Actions to repeat / ways of reaching the bug:* Try using the latest public/or dev build of MM. https://pastebin.com/FzZAd893

*Miniature Pets Dump Link:* https://pastebin.com/UseVc8Yx

Thanks.

**Comment by SXRWahrheit** [comment]
🤔 

https://gyazo.com/9da1d925eaa9f2b7b5aa510c26f08eaf

That screenshot was taken on 12/17, meaning the last update from MPet devs was 12/8. `loadcontainer()` is not an appropriate replacement for the "old" API. It defies logic to force a plugin implementing an API to do the work of the plugin "providing" that API.

**Comment by danielntech** [comment]
Hello @TerraPrimal, we are working closely with the MythicMobs development team to ensure that our community which you are a part of is satisfied, in the upcoming weeks there should come a final update fixing all of the issues. Please reopen if anything was unclear :)

**Comment by SXRWahrheit** [comment]
Why not leave the issue open until the problem is resolved?

**Comment by SXRWahrheit** [comment]
🤔
