### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by mattyokan** [danielntech/miniaturepets#77]
*Suggestion:* 
Provide adequate API documentation and a Javadoc
*How will it improve the plugin:* 
Developers won't have to snoop around the decompiled version of the plugin to work with it, there will be more clear direction on what can/can't be used by developers
*Any examples or additional information:*
Look at most plugins' javadocs, they provide info and helpful methods for developers. I'm interested in integrating miniaturepets with a few of my plugins, they would be great to use...

**Comment by danielntech** [comment]
Hello, [click here](https://miniaturepets.net/docs/) to read our documentation, let me know if that is what you looked for.

**Comment by mattyokan** [comment]
Yes, thank you!
