### ISSUE TITLE
Cannot ride pet

### ISSUE THREAD

**Issue by Klawdek** [danielntech/miniaturepets#79]
*Short description:* 
Cannot ride pet
*Long description:* 

*Actions to repeat / ways of reaching the bug:* 
Selet ride pet from pet menu
*Miniature Pets Dump Link:*
https://pastebin.com/PnGSCyUU

**Comment by danielntech** [comment]
Hey @Klawdek, we were unable to reproduce this error. We ran the plugin in a fresh environment and it worked great, it appears to be one of your plugins conflicting.
