### ISSUE TITLE
Pet gliding bug

### ISSUE THREAD

**Issue by TrollC** [danielntech/miniaturepets#8]
MPets debug: https://pastebin.com/etzvH5Pm
Short desc: So all the time I have my pet summoned it teleports to me when I'm flying and slowly glides down. It's really weird lol
Steps to reproduce: 1. just spawn a pet 2. fly around
Proof: https://youtu.be/PLvmzOY9D48

**Comment by danielntech** [comment]
It has been forwarded for further examination.

**Comment by danielntech** [comment]
Hi this is not a bug, this is just the normal drop rate on Minecraft. I believe it can be changed on "spigot.yml", I'm pretty unsure about that one though.

**Comment by SirBailey** [comment]
Seen the discord post alert this haha, cool.

The reason the pet falls so slowly is that the pet anchor is a chicken (and chickens fall slowly), change the anchor to a pig, sheep or anything else that doesn't fall slowly. Easy fix (note, only MPet 2.0 can do this ).
