### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Klawdek** [danielntech/miniaturepets#80]
*Short description:* 
Get these errors in console.  They just happen every few minutes or so without anyone even using the program
https://pastebin.com/c8UrsUys
*Long description:* 

*Actions to repeat / ways of reaching the bug:* 
Watch console and they appear after a while.  Nobody is even using them.
*Miniature Pets Dump Link:*
dump https://pastebin.com/ChGcTDTs

**Comment by NacOJerk** [comment]
Dump was deleted...

**Comment by danielntech** [comment]
Hi, this was fixed with the latest update, if you still encounter issues please reopen this issue.
