### ISSUE TITLE
Hard to interact with pet [WorldGuard Issue]

### ISSUE THREAD

**Issue by Golicraft** [danielntech/miniaturepets#82]
*Short description:* 
Non OP players can't interact easy with Pets
*Long description:* 
So when right clicking a pet with OP it opens the GUI everytime I click but when I'm deoped it doesn't. Then I need to click about 20 times different locations on the pet to get the GUI opened. This is something to do with WorldGuard! 

Why: Because I tested. I gave myself the worldguard.* permission and then it worked all the time. I have tried different flags such as "Use and Interact" value to TRUE but doesn't work. The deny message from WorldGuard says this:
Hey! Sorry, but you can't change that here.

*Actions to repeat / ways of reaching the bug:* 
WorlGuard 6.1.3
MiniaturePets 2.1.7
Spigot 1.8.8

*Miniature Pets Dump Link:*
Won't send because of private plugin list. Please respect that

**Comment by danielntech** [comment]
Hello, there is no matter of respect involved, in order to provide you support we need your full un-censored `/mpet dump` because we can't recreate issues without it. If you refuse to give us your `/mpet dump` link it's your consideration, but we can't provide support without it.

**Comment by Golicraft** [comment]
The mpet dump link only includes all my plugins and I wont share that. That has nothing todo with the issue I have.

**Comment by danielntech** [comment]
This was fixed and will be posted upon the release of the latest update.
